export { IntakeFeature } from "./intake-feature";
export { HeroSlider } from "./hero-slider";
export { CountriesSection } from "./countries-section";
export { UniversitySlider } from "./university-slider";
export { AboutSection } from "./about-section";
export { AccredianSection } from "./accredian-section";
export { default as WhyChooseUs } from "./why-choose-us";
export { default as EventsSection } from "./event-section";
export { default as FaqSection } from "./faq-section";
export { default as BlogSection } from "./latest-blogs";
